# Generated by Django 4.2.2 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0002_rename_fkey_customer_fk1_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
