# Generated by Django 4.2.2 on 2023-07-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=100)),
                ('partmanufactures', models.CharField(max_length=100)),
                ('partprice', models.IntegerField()),
                ('partcount', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeapp.staff')),
            ],
        ),
    ]
