# Generated by Django 4.2.2 on 2023-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='partimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
