# Generated by Django 4.2.2 on 2023-07-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0005_stock_partimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='partwarranty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
