# Generated by Django 4.2.2 on 2023-07-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0006_stock_partwarranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
