# Generated by Django 4.2.2 on 2023-07-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0007_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeapp.customer')),
            ],
        ),
    ]
