# Generated by Django 4.2.2 on 2023-07-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeapp.order')),
                ('stkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeapp.stock')),
            ],
        ),
    ]
