# Generated by Django 4.2.2 on 2023-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0010_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amt',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
