# Generated by Django 4.2.2 on 2023-07-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0011_cart_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amt',
            field=models.IntegerField(null=True),
        ),
    ]
