# Generated by Django 5.1.3 on 2025-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0014_chat_mechanicbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicbooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mechanicbooking',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
