# Generated by Django 5.1.3 on 2025-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0015_alter_mechanicbooking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
