# Generated by Django 5.1.3 on 2025-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0016_mechanic_lat_mechanic_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='lon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
